// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSpbCqZkVmz1a5bU3fp40gAx-ENrGgGbM',
    appId: '1:841761556204:web:18ca69b7daacb9bbba07c9',
    messagingSenderId: '841761556204',
    projectId: 'shining-axis-326714',
    authDomain: 'shining-axis-326714.firebaseapp.com',
    storageBucket: 'shining-axis-326714.appspot.com',
    measurementId: 'G-V9X72H4DRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ17G3GujhdYCk3As5-VuCwReRKwidRAI',
    appId: '1:841761556204:android:09cf76783f2fdd01ba07c9',
    messagingSenderId: '841761556204',
    projectId: 'shining-axis-326714',
    storageBucket: 'shining-axis-326714.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxYsP8gmvtHTG6EPJYUUS7_8cN-6EI7q8',
    appId: '1:841761556204:ios:5b0308ad5d9bc19bba07c9',
    messagingSenderId: '841761556204',
    projectId: 'shining-axis-326714',
    storageBucket: 'shining-axis-326714.appspot.com',
    iosClientId: '841761556204-3ub1pvcgtmg5slpkdgacgg8tsre52kju.apps.googleusercontent.com',
    iosBundleId: 'com.example.timetable',
  );
}
